

const data =[{"id":1,"title":"Mitsubishi","desc":"Nondisplaced fracture of medial malleolus of unspecified tibia, subsequent encounter for open fracture type I or II with nonunion","img":"http://dummyimage.com/181x100.png/5fa2dd/ffffff","price":54.4,"l_desc":"Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat."},
{"id":2,"title":"Mazda","desc":"Driver of heavy transport vehicle injured in collision with unspecified motor vehicles in nontraffic accident, subsequent encounter","img":"http://dummyimage.com/230x100.png/ff4444/ffffff","price":31.5,"l_desc":"Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum."},
{"id":3,"title":"Toyota","desc":"Contact with hot household appliance, undetermined intent","img":"http://dummyimage.com/122x100.png/cc0000/ffffff","price":58.3,"l_desc":"Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis."},
{"id":4,"title":"Chevrolet","desc":"Unspecified enophthalmos, bilateral","img":"http://dummyimage.com/158x100.png/ff4444/ffffff","price":58.7,"l_desc":"Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus."},
{"id":5,"title":"Hyundai","desc":"Trisomy 21, mosaicism (mitotic nondisjunction)","img":"http://dummyimage.com/169x100.png/ff4444/ffffff","price":65.7,"l_desc":"Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus."},
{"id":6,"title":"Buick","desc":"Strain of muscle and tendon of front wall of thorax, subsequent encounter","img":"http://dummyimage.com/249x100.png/dddddd/000000","price":90.3,"l_desc":"Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede."},
{"id":7,"title":"Land Rover","desc":"Corrosion of unspecified degree of right axilla","img":"http://dummyimage.com/100x100.png/5fa2dd/ffffff","price":78.4,"l_desc":"Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat."},
{"id":8,"title":"Mercury","desc":"Maternal care for other isoimmunization, unspecified trimester, fetus 1","img":"http://dummyimage.com/164x100.png/ff4444/ffffff","price":26.9,"l_desc":"Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero."},
{"id":9,"title":"Chevrolet","desc":"Unspecified superficial injury of left wrist, sequela","img":"http://dummyimage.com/154x100.png/ff4444/ffffff","price":94.2,"l_desc":"Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis."},
{"id":10,"title":"Honda","desc":"Other specified injury of femoral vein at hip and thigh level, right leg","img":"http://dummyimage.com/239x100.png/cc0000/ffffff","price":38.0,"l_desc":"Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus."},
{"id":11,"title":"Oldsmobile","desc":"Nondisplaced fracture of medial malleolus of right tibia, subsequent encounter for open fracture type I or II with malunion","img":"http://dummyimage.com/200x100.png/5fa2dd/ffffff","price":55.3,"l_desc":"Fusce consequat. Nulla nisl. Nunc nisl."},
{"id":12,"title":"Audi","desc":"Unspecified car occupant injured in collision with other nonmotor vehicle in traffic accident, sequela","img":"http://dummyimage.com/107x100.png/ff4444/ffffff","price":37.6,"l_desc":"Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus."},
{"id":13,"title":"Toyota","desc":"Nondisplaced fracture of proximal phalanx of left little finger, subsequent encounter for fracture with delayed healing","img":"http://dummyimage.com/190x100.png/5fa2dd/ffffff","price":59.4,"l_desc":"Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem."},
{"id":14,"title":"Chevrolet","desc":"Unspecified fracture of shaft of humerus","img":"http://dummyimage.com/193x100.png/dddddd/000000","price":75.0,"l_desc":"Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi."},
{"id":15,"title":"Pontiac","desc":"Posterior dislocation of lens, unspecified eye","img":"http://dummyimage.com/124x100.png/ff4444/ffffff","price":78.7,"l_desc":"Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus."},
{"id":16,"title":"Cadillac","desc":"Corrosion of second degree of right axilla","img":"http://dummyimage.com/153x100.png/cc0000/ffffff","price":61.5,"l_desc":"Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat."},
{"id":17,"title":"Volkswagen","desc":"Gonococcal infection of musculoskeletal system, unspecified","img":"http://dummyimage.com/120x100.png/ff4444/ffffff","price":58.0,"l_desc":"Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros."},
{"id":18,"title":"Mercedes-Benz","desc":"Greenstick fracture of shaft of unspecified ulna, initial encounter for closed fracture","img":"http://dummyimage.com/178x100.png/ff4444/ffffff","price":91.9,"l_desc":"Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit."},
{"id":19,"title":"Ford","desc":"Unspecified dislocation of other finger, initial encounter","img":"http://dummyimage.com/211x100.png/dddddd/000000","price":45.6,"l_desc":"Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris."},
{"id":20,"title":"Land Rover","desc":"Displaced oblique fracture of shaft of right tibia, subsequent encounter for open fracture type I or II with routine healing","img":"http://dummyimage.com/208x100.png/ff4444/ffffff","price":22.8,"l_desc":"Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi."}]
export {data};